  json.extract! user,
    :id,
    :email,
    :name,
    :description,
    :image_url,
    :profile_picture,
    :thumbnail_image,
    :search_image,
    :goal,
    :percent_funded,
    :amount_funded
