# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


user1 = User.create(email: "user@example.com", name: "John", password: "password")
user2 = User.create(email: "antoher@example.com", name: "Bob", password: "password")
user3 = User.create(email: "water@example.com", name: "Pablo", password: "password")
user4 = User.create(email: "yeyey@example.com", name: "Rudy", password: "password")
user5 = User.create(email: "antohyeyeyer@example.com", name: "Ansel", password: "password")
user6 = User.create(email: "wawawawater@example.com", name: "Alejandro", password: "password")
Art.create(artist_id: user1.id, title: "tree", description: "great", image_file_name: "https://www.johncostanza.com/images/painting_tree.2.jpg")
Art.create(artist_id: user1.id, title: "tree", description: "great", image_file_name: "https://www.johncostanza.com/images/painting_tree.2.jpg")
Art.create(artist_id: user1.id, title: "tree", description: "great", image_file_name: "https://www.johncostanza.com/images/painting_tree.2.jpg")
Art.create(artist_id: user1.id, title: "tree", description: "great", image_file_name: "https://www.johncostanza.com/images/painting_tree.2.jpg")
Art.create(artist_id: user2.id, title: "tree", description: "great", image_file_name: "https://www.johncostanza.com/images/painting_tree.2.jpg")
Art.create(artist_id: user2.id, title: "tree", description: "great", image_file_name: "https://www.johncostanza.com/images/painting_tree.2.jpg")
Art.create(artist_id: user3.id, title: "tree", description: "great", image_file_name: "https://41.media.tumblr.com/cd6535a0f5c952864f91c4a50209f57b/tumblr_inline_nq4cy3UNyz1skc9nk_540.jpg")
Art.create(artist_id: user1.id, title: "tree", description: "great", image_file_name: "https://greatestpainting.com/images/paintings/monalisa.jpg")
Art.create(artist_id: user4.id, title: "tree", description: "great", image_file_name: "https://www.johncostanza.com/images/painting_tree.2.jpg")
Art.create(artist_id: user5.id, title: "tree", description: "great", image_file_name: "https://www.johncostanza.com/images/painting_tree.2.jpg")
Art.create(artist_id: user6.id, title: "tree", description: "great", image_file_name: "https://www.johncostanza.com/images/painting_tree.2.jpg")
Art.create(artist_id: user5.id, title: "tree", description: "great", image_file_name: "https://41.media.tumblr.com/cd6535a0f5c952864f91c4a50209f57b/tumblr_inline_nq4cy3UNyz1skc9nk_540.jpg")
Art.create(artist_id: user3.id, title: "tree", description: "great", image_file_name: "https://greatestpainting.com/images/paintings/monalisa.jpg")
Category.create(name: "Paint", image_url: "https://greatestpainting.com/images/paintings/monalisa.jpg")
Category.create(name: "Photography", image_url: "https://greatestpainting.com/images/paintings/monalisa.jpg")
Category.create(name: "Mural", image_url: "https://greatestpainting.com/images/paintings/monalisa.jpg")
Category.create(name: "Fashion", image_url: "https://greatestpainting.com/images/paintings/monalisa.jpg")
Categorizing.create(category_id: 1, categorizable_type: "User", categorizable_id: 1)
Categorizing.create(category_id: 1, categorizable_type: "User", categorizable_id: 2)
Categorizing.create(category_id: 1, categorizable_type: "User", categorizable_id: 3)
Categorizing.create(category_id: 1, categorizable_type: "User", categorizable_id: 4)
Categorizing.create(category_id: 2, categorizable_type: "User", categorizable_id: 1)
Categorizing.create(category_id: 2, categorizable_type: "Art", categorizable_id: 1)
Categorizing.create(category_id: 2, categorizable_type: "Art", categorizable_id: 2)
Categorizing.create(category_id: 3, categorizable_type: "Art", categorizable_id: 3)
Categorizing.create(category_id: 3, categorizable_type: "Art", categorizable_id: 4)
Categorizing.create(category_id: 3, categorizable_type: "Art", categorizable_id: 1)
